/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author leonardo
 */
import Conexion.Conectar;
import Formularios.UsuariosAdministrar;
import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private String usuarioID = "1";
    private String usuarioNombre = "admin";
    private String usuarioTipo = "admin";
    private Conectar conector = null;
    private int[] combinar = {0,0,0,0};
    
    private boolean administrador = false,supervisor = false,cajero = false;
    
    public void validarTipoUsuario(){
        administrador = false;
        supervisor = false;
        cajero = false;
        switch(this.usuarioTipo){
            case "administrador":
                this.administrador = true;
                break;
            case "supervisor":
                this.supervisor = true;
                break;
            case "cajero":
                this.cajero = true;
                break;
        }
    }
    
    public void setUsuarioTipo(String usuarioTipo){
        this.usuarioTipo = usuarioTipo;
    }
    
    public void setUsuarioID(String usuarioID){
        this.usuarioID = usuarioID;
    }
    
    public void setUsuarioNombre(String usuarioNombre){
        this.usuarioNombre = usuarioNombre;
    }
    
    public void setConector(Conectar conector){
        this.conector = conector;
    }
    
    
    public Menu(Conectar conector, String usuarioID, String usuarioNombre, String usuarioTipo){
        initComponents();
        this.setConector(conector);
        this.setUsuarioID(usuarioID);
        this.setUsuarioNombre(usuarioNombre);
        this.setUsuarioTipo(usuarioTipo);
        this.validarTipoUsuario();
        this.jLabelUsuarioConectado.setText(usuarioNombre);
        this.setLocationRelativeTo(null);
        
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }
    
    public void cliente(){
        if(this.administrador || this.cajero || this.supervisor){
            ClienteAdministrar cliente = new ClienteAdministrar(this.conector, this.usuarioID, this.usuarioNombre);
            cliente.setYo(cliente);
            cliente.setVisible(true);
        }
    }
    
    
    public void Proveedor(){
        if(this.administrador || this.supervisor ){
            ProveedorAdministrar proveedor = new ProveedorAdministrar(this.conector, this.usuarioID, this.usuarioNombre);
            proveedor.setYo(proveedor);
            proveedor.setVisible(true);
        }
    }
    
    
    public void Producto(){
        if(this.administrador || this.supervisor){
            ProductoAdministrar producto = new ProductoAdministrar(this.conector, this.usuarioID, this.usuarioNombre);
            producto.setVisible(true);
        }
    }
    
    
    public void ComprarProducto(){
        if(this.administrador || this.supervisor){
            CompraProductoAdministrar compra = new CompraProductoAdministrar(this.conector, this.usuarioID, this.usuarioNombre);
                compra.setYo(compra);
                compra.setVisible(true);            
        }
    }
    
    
    public void usuario(){
        if(this.administrador || this.cajero || this.supervisor){
            UsuariosAdministrar usuario = new UsuariosAdministrar(this.conector,this.usuarioID,this.usuarioNombre);
            usuario.setVisible(true);
        }
    }
    
    public void acercade(){
        if(this.administrador || this.cajero || this.supervisor){
            AcercaDe acercaDe = new AcercaDe();
            acercaDe.setVisible(true);
        }
    }
    
    public void TipoTelefono(){
        //TipoTelefonoAdministrar
        if(this.administrador || this.cajero || this.supervisor){
            TipoTelefonoAdministrar tipoTelefono = new TipoTelefonoAdministrar(this.conector, this.usuarioID, this.usuarioNombre);
            tipoTelefono.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsuarioConectado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemProveedor = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Proveedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(25, 82, 68));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(25, 82, 68));

        jLabel2.setText("Usuario:");

        jLabelUsuarioConectado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuarioConectado.setText("Usuario Conectado");

        jMenu1.setText("Inicio");

        jMenuItem2.setText("Cambiar clave");
        jMenuItem2.setToolTipText("");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenuItemProveedor.setText("Administrar");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Usuario");
        jMenuItem5.setToolTipText("");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem5MousePressed(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuItemProveedor.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Cliente");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem6MousePressed(evt);
            }
        });
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuItemProveedor.add(jMenuItem6);

        Proveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Proveedor.setText("Proveedor");
        Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProveedorMousePressed(evt);
            }
        });
        jMenuItemProveedor.add(Proveedor);

        jMenuBar1.add(jMenuItemProveedor);

        jMenu3.setText("Ayuda");

        jMenuItem4.setText("Acerca de...");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuarioConectado))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MousePressed
        // TODO add your handling code here:
        this.acercade();
    }//GEN-LAST:event_jMenuItem4MousePressed

    private void jMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
        // TODO add your handling code here:
        this.usuario();
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //System.out.println(evt.getKeyChar());
        System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == KeyEvent.VK_CONTROL){
            this.combinar[0] = KeyEvent.VK_CONTROL;
            
        }else if(evt.getKeyCode() == KeyEvent.VK_SHIFT){
            
        }else if(evt.getKeyCode() == KeyEvent.VK_U){
            this.combinar[1] = KeyEvent.VK_U;
            if((this.combinar[0] == 17) && (this.combinar[1] == 85)){
            this.usuario();
        }
        }else if(evt.getKeyCode() == KeyEvent.VK_C){
            this.combinar[1] = KeyEvent.VK_C;
            if((this.combinar[0] == KeyEvent.VK_CONTROL) && (this.combinar[1] == KeyEvent.VK_C)){
                this.cliente();
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_P){
            this.combinar[1] = KeyEvent.VK_P;
            if((this.combinar[0] == KeyEvent.VK_CONTROL) && (this.combinar[1] == KeyEvent.VK_P)){
                this.Proveedor();
            }
        }else{
            System.out.println("4"+evt.getKeyCode());
            this.combinar[0] = 0;
            this.combinar[1] = 0;
        }
        /*
        if(evt.getKeyCode() == KeyEvent.VK_U){
            JOptionPane.showMessageDialog(null,""+evt.getKeyChar());
        }
        if(evt.getKeyCode() == KeyEvent.VK_CONTROL){
            JOptionPane.showMessageDialog(null,""+evt.getKeyChar());
        }
        if(evt.getKeyCode() == KeyEvent.VK_CONTROL && (evt.getKeyCode() == KeyEvent.VK_U)){
            JOptionPane.showMessageDialog(null,""+evt.getKeyChar());
        }
        */
        
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MousePressed
        // TODO add your handling code here:
        this.cliente();
    }//GEN-LAST:event_jMenuItem6MousePressed

    private void ProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedorMousePressed
        // TODO add your handling code here:
        this.Proveedor();
    }//GEN-LAST:event_ProveedorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUsuarioConectado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuItemProveedor;
    // End of variables declaration//GEN-END:variables
}
